### ISSUE TITLE
Using Element in FAQ Custom Post Type (CPT)

### ISSUE THREAD

**Issue by michelbayard** [Theme-Fusion/Fusion-Builder-Sample-Add-On#16]
Hello ThemeFusion,

is there a known conflict with using elements with the FAQ custom post type (CPT)?

Thank you in advance!

**Comment by lukeabeck** [comment]
Hey @michelbayard !

Not that we know of, what exact setup are you using?

**Comment by michelbayard** [comment]
Hello @lukeabeck!

thank you for the reply. See the attached file for reference; this was confirmed on a user's site and our staging installation. Should access be required, please let me know and I'll email them.

Michel
![screen shot 2017-07-03 at 4 58 15 pm](https://user-images.githubusercontent.com/14185663/27807777-042eae92-6011-11e7-9fc7-1229abe91d45.png)
![screen shot 2017-07-03 at 4 58 56 pm](https://user-images.githubusercontent.com/14185663/27807778-04333ffc-6011-11e7-858d-1d9d080eef00.png)

**Comment by maximus80** [comment]
Hello @michelbayard!

Can you please send me login data to mark@theme-fusion.com and also some explanation on what happens that is not expected?

Thank you!

**Comment by michelbayard** [comment]
Hello **@maximus80**!

Thank you for the reply! Credentials sent via email.

**Comment by maximus80** [comment]
Thanks for the credentials.
Having checked the site, the issue is dynamically loaded/animated content. So I guess some JS is involved when loading the before/after element. In that case, because of the collapsed state of the faq element on load, the elements inside it can’t be properly loaded/sized.
We have similar dynamically created elements like youtube etc. We do solve this by retriggering the needed JS on toggle click. Which is also my suggestion for you. We basically use this click event:

```
jQuery( document ).on( 'click dblclick', '.fusion-accordian .panel-title a', function( e ) {
// Your code here.
});
```

You can also take a look at fusion-toggles.js in fusion-builder/assets/js/general folder.

Hope that helps.
