### ISSUE TITLE
Equal Heights  for Blog shortcode grid layout

### ISSUE THREAD

**Issue by ghost** [Theme-Fusion/Fusion-Builder-Sample-Add-On#17]
Hi.
I am the author of CPT add-on and now try to make it work with Avada 5.3. With Equal Heights grid layout I see screen re-renders when I resize the window. It causes some issues for me. Are there some JS involved in managing Equal Heights option? Can you point the JS file and functions that are involved in this process, please.

**Comment by lukeabeck** [comment]
Hey @waubau can you show me a video of what you are referring to? I do not see a re-render when I resize.

@Theme-Fusion/developers can assist further

**Comment by maximus80** [comment]
Hey @waubau,

the grid layouts do use isotope, so some recalculation on the position of items is done, if you resize the window.
Additionally, if you use equal heights, because of the above the amount of items per "row" and also their natural height can change. That means that after a resize is finished, equal heights have to be recalculated as well. All of that is calculated on the fly, so heights just are reset after resize ends.

The actual calcs for blog element are in `fusion-blog.js`, in `Avada/includes/lib/assets/min/js/general` folder. The main function ivolved is `fusionCalculateBlogEqualHeights()`, which is invoked in a few placed in that file.

Similar is true for the portfolio element. The file `avada-portfolio.js` is located in `fusion-core/js/min` folder, main function name being `fusionCalculatePortfolioEqualHeights()`.

If you want unminifiedfile versions, please contact us at support@theme-fusion, and we'll send them to you.

Thanks!

**Comment by ghost** [comment]
@lukeabeck 
Hi, please find the video here. See with sound on to hear my explanations. 
https://youtu.be/e2rH-4BL-fM

**Comment by maximus80** [comment]
Seeing your video, it does not look like you are using the release candidate of Avada 5.3, are you?
If you are please open a ticket in the beta repo, where it is easier for us to check. Also it would be good if we could access your site for testing.

The on load issue in your vide is something that should not happen, all elements should be rendered correctly, which is the case in our tests, so it would really help to see your site.

As explained above, on a page resize some rerendering is inevitable, so that is more of a limitation and not a bug.

**Comment by ghost** [comment]
@maximus80 
I am using the latest code from github.  In Avada admin welcome screen logo it only says 5.3 in the right white and green square so I can't figure out what the version realy is. But anyway I do not open the issue because your Blog shotcode works fine. It does rerenders when seen in dev tools but it does not result in visual effect. So I would like to have a look at your JS first to find out what might be the issue.  If it does not work out  I may need some more help. 

Where do you launch those JS files? I guess you tried to keep everithing in the shortcoide file in the previous versions but I do not see references to the js files you mentioned above in shortcode php files.

**Comment by maximus80** [comment]
You can take a look at `Avada/includes/class-fusion-scripts.js`. That script is also needed for the main blog page and the archives, which is why it is not enqueued in the shortcode main file.

**Comment by ghost** [comment]
thanks,
I have also sent the request for JS files to support@theme-fusion.com

**Comment by ghost** [comment]
@lukeabeck, @maximus80 
Hi!
I still have not received any JS file from you and I still have the problem of my equal size height calculating as 0. Can you please share your js files?

and there is no  Avada/includes/class-fusion-scripts.js file.

**Comment by m1chelangel0** [comment]
@waubau I do apologize for this. This was lost in communication. I did see your email to support at and the Git communication therein and misread it. I did not reply because I though this was handled via the Git thread

I only handle the support side of things, not development. I am trying to figure out just now what files you need as the theme does not include unminified versions. I will reply back shortly

**Comment by m1chelangel0** [comment]
@waubau Email is sent with the fils you are looking for, please check your inbox 

Thank you

**Comment by mikka23** [comment]
Hi @waubau 

The zip sent should contain the unminified JS files used in each plugin.  The folder with FL means the JS script is shared and exists in both Fusion Builder and Avada (blog does for example, so you will find that in FL folder).

The file Markus must have been referring to is Avada/includes/lib/inc/class-fusion-scripts.php which is what calls the fusion-blog JS.

**Comment by maximus80** [comment]
Sorry guys, made a copy and paste error, regarding the script including class URL. Thanks @mikka23 for pointing out :+1:

**Comment by slava-lu** [comment]
Thanks for your help. I pinpointed the problem but struggle a bit with a solution.  The issue is that when it comes to calculation the post height in the second row you use this formula
`height = parseInt( jQuery( this ).parent().height() ) - top;`
and somehow your Blog shortcode calculates it right  but my shortcode makes the wrong calculation of the initial parent height.  When I resize the screen `parent().height()` is calculated correctly.  And to be honest I don't very much understand how you can calculate the parent height without  knowing the child one yet? 
can you guide me to some direction here please?

**Comment by ghost** [comment]
I fixed it. I was some wrong calculation of the min height. You can close it.

**Comment by yawalkar** [comment]
Thanks @waubau 👍
