### ISSUE TITLE
Wrong Icon in Fusion Builder

### ISSUE THREAD

**Issue by Zortrox** [Theme-Fusion/Fusion-Builder-Sample-Add-On#22]
I'm making an addon and have an issue in the `fusion_builder_map` function where multiple `'type' => 'iconpicker'` elements are showing the same icon.  The shortcode still uses the correct icon name though.  If it matters, the first `iconpicker` is in the "General" group, while the other two are in the "Design" group.

Also, I have about 80 different shortcode mappings with dependencies if that helps resolve this.

**EDIT:** I didn't realize I could upload images before...
![image](https://user-images.githubusercontent.com/10609756/35889467-4bacdfae-0b61-11e8-8fa4-ca46718e9fe0.png)
![image](https://user-images.githubusercontent.com/10609756/35889480-57ea3398-0b61-11e8-8d3f-b0bde76d5634.png)
![image](https://user-images.githubusercontent.com/10609756/35889530-8aedc4e4-0b61-11e8-9bed-e00d77b6a613.png)

**Comment by maximus80** [comment]
Hello,

thanks for reporting this! We already had this on our list, and it will be fixed in our upcoming new version in a few weeks.
You can download an updated file here. Please copy it to the fusion-builder/js folder.
[fusion-builder.zip](https://github.com/Theme-Fusion/Fusion-Builder-Sample-Add-On/files/1701930/fusion-builder.zip)

The actual icon selection is correct in the shortcode, but when using multiple instances, currently in the builder view, for all instances always the icon of the first selector is highlighted.

Sorry for the inconvenience!

**Comment by lukeabeck** [comment]
@Zortrox if this is an add on you plan to sell and would like help advertising it, please contact me at info@theme-fusion.com

Thanks and best of luck

**Comment by Zortrox** [comment]
@maximus80, thank you for the quick reply and temporary fix!  I should have looked through the issues a bit more.  😅

@lukeabeck, thank you for the offer!  I'm good at the moment, but I'll keep that in mind for future addons!

Closing this since it will be fixed in a few weeks.

**Comment by maximus80** [comment]
You are welcome! Good luck with the new add-on :+1:
