### ISSUE TITLE
Front End Fusion builder info

### ISSUE THREAD

**Issue by slava-lu** [Theme-Fusion/Fusion-Builder-Sample-Add-On#37]
Hi, I am the CPT plugin developer. I have been testing Avada 6.0 and my plugins have some issues in front-end mode. 
Can you please share some info how elements are rendered in the front-end mode. 

1. Which files are involved
2. How shortcode options are read,  displayed and saved
3. If my plugin uses custom post types, should this post type be enabled for REST API to work properly?

Thanks

**Comment by mikka23** [comment]
Hi @slava-lu 

1.  Lots of files 😁 Too many to list, it would be better to have more specific about the plugin in order to assist.
2.  The same way as the back-end for the most part.  Just for the front-end some extra data is required.
3.  Right now the live editor does not require REST api so this should be fine regardless, unless you specifically need it for you plugin.

Copying an earlier reply to a similar ticket on our beta repo:
I also created a barebones example of an element with a custom view and template to show you the general construction.

Idea is more or less that your normal element CSS and JS will exist and fire as normal. But instead of using PHP to create the markup for your element, it is done with JS. That is done via a combination of a JS view and an underscore template.

In the JS view there are various functions to help with different operations. For example afterPatch is run after the element render has been updated. So if you element requires JS to be re-init, you can do it here.

Details can be found here - https://github.com/Theme-Fusion/Fusion-Builder-Sample-Add-On/tree/front-end

Go to the sample builder add-on repo and switch to the front-end branch (newly created). There are some WIP details about the API in the read me. If you download the zip it provides an example of a simple element. Download the zip from the repo, install and activate as a plugin, then go to Fusion Builder > Settings and enable the Hello World element. Now you should have a new element in the back-end and front-end builder. I added some comments to the files as further help.

**For further assistance, if you can post in our beta repo with some specifics about the problems you face or how you are trying to implement your add-on into the front-end then I can help you out.  It would be better to do it there since 6.0 is still not publicly released.**
