### ISSUE TITLE
Add-on name doesn't support ampersands

### ISSUE THREAD

**Issue by dloewen** [Theme-Fusion/Fusion-Builder-Sample-Add-On#4]
Giving the element a title with an ampersand displays its HTML entity "`&amp;`" instead of "&".

**Comment by yawalkar** [comment]
If you set the element title or the add-on name with the **`esc_attr`**, it will show the html code instead of the entity. So, instead of this - 

`'name'              => esc_attr__( 'Mail & Messages', 'fusion-builder' ),`

use this - 

`'name'              => __( 'Mail & Messages', 'fusion-builder' ),`
